### ISSUE TITLE
Bot info is making the bot not respond

### ISSUE THREAD

**Issue by BarleyTheFoxDroplettTheReindeer** [NonbinaryWiki/BinaryBot#61]
**Describe the bug**
Bot info isn't working.

**To Reproduce**
/botinfo

**Expected behavior**
Give me bot information.

**Comment by NeoMahler** [comment]
Hi @BarleyTheFoxDroplettTheReindeer ! The botinfo command is an owner-only command. So you can only use it if you're hosting the bot yourself. Hope this answers the issue!

**Comment by NeoMahler** [comment]
@BarleyTheFoxDroplettTheReindeer sorry for the confusion! It's a command for the owner of the bot, not for the server owner. It simply gives you the number of servers the bot is in. It's relevant information for the bot's owner (i.e. the person who installed it and is running it), but not for the owner of an individual server.
